### ISSUE TITLE
Dependencies no longer available? 

### ISSUE THREAD

**Issue by mehmetg** [inconshreveable/go-tunnel#3]
"code.google.com/p/go.net/proxy"
"code.google.com/p/log4go"

Seem to be broken? maybe they have moved? 

Also, is the underlying service still available?

**Comment by agrison** [comment]
+1

**Comment by mehmetg** [comment]
I managed to compile the code... other problems happen with server to connect to, etc. The code is out of date... Just an FYI.

**Comment by agrison** [comment]
Yep I got it compiling too by using x/net/proxy et log4go elsewhere on GitHub but it does not work as expected. Leaving it there, too bad!

**Comment by mehmetg** [comment]
I think this lib has been abandoned when ngrok 2 came out. Understandably non paying users get little support and help.

**Comment by inconshreveable** [comment]
Yeah, there used to be an example service of this running, but I'm no longer running it. Parts of this library were used in ngrok2, but it's no longer maintained. It's possible that I may extract that out of ngrok2 and make it available to the community, but that's a function of the product roadmap and available time. At the moment, you should consider this library deprecated and only for informational reference uses.  I'd be happy to accept pull requests to get it to at least compile again.

**Comment by mehmetg** [comment]
Here you go. I also used local references for the benefit of people forking. 
https://github.com/inconshreveable/go-tunnel/pull/4

**Comment by inconshreveable** [comment]
i've fixed these, closing
